### ISSUE TITLE
PyPI Releases with Tests

### ISSUE THREAD

**Issue by arkamar** [corenting/immutabledict#196]
Hi, would it be possible to include tests in the PyPI release? It would be beneficial especially for the Gentoo package because we could use the PyPI source and still be able to check if the package works in our environment.

**Comment by corenting** [comment]
Hello ! I fixed the issue with version 2.2.4 that just got released on PyPI, the [sdist download](https://files.pythonhosted.org/packages/ab/96/548ee1a774062b2bec740ef03ab427f20e802d66b1db23a42ba20cb88121/immutabledict-2.2.4.tar.gz) now include the tests.

**Comment by arkamar** [comment]
Thanks for a quick response and release!
