### ISSUE TITLE
Class name should be ImmutableDict

### ISSUE THREAD

**Issue by cool-RR** [corenting/immutabledict#23]
I think that the name of the class should be `ImmutableDict` rather than `immutabledict`. Python's standard library uses lower-case names like that, but it's standard for third-party packages to use camel-case for class names.

**Comment by corenting** [comment]
I agree, I keeped it like this for now to have a naming scheme similar in casing to `frozendict`. I may change it for a further release to have a more standard naming schema :)

**Comment by licht1stein** [comment]
It doesn't have to in this case. Look at `namedtuple`

**Comment by corenting** [comment]
Yeah I think it's good to do like `namedtuple` and keep something similar to `dict`, `frozenset`, and `tuple`, especially since it was already the case in `frozendict`, so I will close this issue.
