### ISSUE TITLE
Why does `__init__` exist?

### ISSUE THREAD

**Issue by spacether** [corenting/immutabledict#239]
Why does `__init__` exist for this class?
Should an immutable class do all setup in `__new__` and not need to invoke `__init__` at all?
My understanding is that yes it should.
For example tuple does not need to invoke init to return back the fully formed instance, it only needs new.

How about moving the `__init__` setup into the `__new__` method and releasing a new major version with the update?
Hmm doing that might require that the class inherit from tuple or namedtuple to be able to store the hash and dict with type hints.

**Comment by corenting** [comment]
Hello ! Thanks for reporting the issue. 
The init code was not changed since the original frozendict, I will see if it can be improved without impacting the usage and the typing.

**Comment by spacether** [comment]
@corenting the PR that I created on your repo will resolve this issue if merged. When you have some time can you review it?

**Comment by corenting** [comment]
Sorry for the late answer and thanks for the MR ! I will try to take some time to review it

**Comment by corenting** [comment]
The MR was merged, thanks again. Closing the issue at will be included in the next release.

**Comment by spacether** [comment]
Thanks for the merge!
