### ISSUE TITLE
Link from PyPI to GitHub is confusing 

### ISSUE THREAD

**Issue by cool-RR** [corenting/immutabledict#24]
If you visit the PyPI page and look for the GitHub link, you're most likely to see the link to the previous GitHub repo, which is not what you want. If you read the text you see it's the previous version, but many viewers don't read the text.

I think it'll be a legitimate decision to drop the link to the previous repo, to avoid any confusion. The idea of a frozen dict has been redone by many people, me included, and indeed most of the heavy lifting is done by `collections.abc.Mapping`.

**Comment by corenting** [comment]
The README was updated to be more clear in 1.1.0, I kept the link to the old project but changed the presentation to be more clear and also added some examples:
