### ISSUE TITLE
How about making an immutabledict class where the value is covariant?

### ISSUE THREAD

**Issue by spacether** [corenting/immutabledict#243]
How about making an immutabledict class where the value is covariant?
Other immutable containers are all covariant (Union, Tuple Sequence etc).
Because the _K is by default not covariant, my type hints did not work when they should have.
This was uncovered here: https://github.com/python/mypy/issues/15710

Note: the copy method must be removed if you do that per pylance or mypy

**Comment by corenting** [comment]
Fixed with #244 , closing the issue
