### ISSUE TITLE
[Feature request] Add intersphinx mapping via sphinx doc 

### ISSUE THREAD

**Issue by matthiasdiener** [corenting/immutabledict#270]
This is useful for documenting classes etc. that use an immutabledict. Maybe readthedocs could be a location for it?

**Comment by corenting** [comment]
Hello, I could indeed add a small documentation page for the library, I will look into it. Thanks for the suggestion.

**Comment by corenting** [comment]
I published a small sphinx documentation here: https://immutabledict.corenting.fr/ .
Closing the issue.
