### ISSUE TITLE
Support more typing

### ISSUE THREAD

**Issue by Callek** [corenting/immutabledict#47]
Addition of the py.typed makes calling `immuteabledict()` in a typed context warn if we have `disallow_untyped_calls` defined for mypy...

I suggest the addition of many of the typings that frozendict has be added here: https://github.com/python/typeshed/blob/4b4ced5fa0418f626033d88702833d3185bbf18f/stubs/frozendict/frozendict.pyi#L8

**Comment by corenting** [comment]
Thanks for the report and sorry for the delay of the answer !
I added more types in the 2.0.0 version so I'm closing the issue.

If there are still some problems feel free to open another issue.
